# Generated by Django 5.2.12 on 2026-03-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_alter_task_priority_alter_task_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="attachment_link",
            field=models.URLField(
                blank=True,
                help_text="Optional link to Google Drive, OneDrive, or any external resource",
                null=True,
            ),
        ),
    ]
