# Generated by Django 5.2.12 on 2026-03-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_task_attachment_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="organization_id",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="app_purpose",
            field=models.CharField(
                choices=[
                    ("PERSONAL", "Personal Productivity"),
                    ("TEAM", "Organization Team Coordination"),
                ],
                default="PERSONAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="organization_id",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="staff_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="task",
            name="organization_id",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name="task",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("PERSONAL", "Personal"),
                    ("DEPARTMENT", "Department"),
                    ("ORGANIZATION", "Organization"),
                ],
                default="PERSONAL",
                max_length=20,
            ),
        ),
    ]
