# Generated by Django 5.2.12 on 2026-08-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_profile_organization_referral_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_nature',
            field=models.CharField(choices=[('ORIDINARY', 'Oridinary Task'), ('UNFINISHED_WORK', 'Unfinished Work')], default='ORIDINARY', max_length=30),
        ),
    ]
