# Generated by Django 5.2.12 on 2026-08-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_task_nature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_nature',
            field=models.CharField(choices=[('ORDINARY', 'Oridinary Task'), ('UNFINISHED_WORK', 'Unfinished Work')], default='ORDINARY', max_length=30),
        ),
    ]
