# Generated by Django 5.2.12 on 2026-08-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_department_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
